# Création d'un container Docker servant au stockage des données de jeu
services:
  postgres-game:
    image: postgres:alpine
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: game
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - game:/var/lib/postgresql
  postgres-users:
    image: postgres:alpine
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: users
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - users:/var/lib/postgresql
volumes:
  game:
  users: