spring.application.name=users
server.port=${BACKEND_USER_PORT}

spring.datasource.url=jdbc:postgresql://postgres-users:${POSTGRES_USER_PORT}/${POSTGRES_USER_DB}
spring.datasource.username=${POSTGRES_USER_USER}
spring.datasource.password=${POSTGRES_USER_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
