spring.application.name=square_game
server.port=${BACKEND_GAME_PORT}
spring.main.allow-bean-definition-overriding=true

spring.datasource.url=jdbc:postgresql://postgres-game:${POSTGRES_GAME_PORT}/${POSTGRES_GAME_DB}
spring.datasource.username=${POSTGRES_GAME_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuration pour jdbc :
#spring.sql.init.mode=always

# configuration avec jba :
spring.jpa.hibernate.ddl-auto=update

game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

game.taquin.default-player-count=1
game.taquin.default-board-size=4

spring.messages.basename=messages
spring.messages.encoding=UTF-8
